---
# tasks file for tomcat

- name: Install Tomcat
  apt:
   name: tomcat9
   state: present
    
- name: Start Tomcat
  service:
    name: tomcat9
    state: started

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

