---

- name: Install and start Tomcat Server
  hosts: all
  become: true

  tasks:
    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present
    - name: Start Tomcat
      service:
        name: tomcat9
        state: started

