pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'javac Hello_world.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java Hello_world'
            }
        }
    }
}
