pipeline {
    agent any

    stages {
        
	stage('Pre-Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
//	stage('Build') {
  //          steps {
		// Compile Java code
    //            sh 'javac Hello_world.java'
      //      }
//        }
//        stage('Run') {
 //           steps {
   //             sh 'java Hello_world'
   //         }
  //      }
    }
}
